---
- name: Include packages.yml
  include: packages.yml
  when: packages_ansible_distribution[ansible_distribution] is defined and
        ansible_distribution_major_version|int in packages_ansible_distribution[ansible_distribution]
  tags:
    - packages
