---
- name: Init empty packages list
  set_fact:
    packages_list: '{{ []  }}'

- name: Append package to packages list
  set_fact:
    packages_list: "{%- if  item[ansible_distribution] is defined
                        and item[ansible_distribution].name is defined %}
                    {{-     packages_list + [item[ansible_distribution].name] }}
                    {%- else %}
                    {{-     packages_list + [item.name] }}
                    {%- endif %}"
  with_items: '{{ packages }}'
  when: not ( item[ansible_distribution] is defined and
              item[ansible_distribution]['version'] is defined and
              ansible_distribution_major_version not in item[ansible_distribution]['version'] ) and
        not ( item[ansible_distribution] is defined and
              item[ansible_distribution]['disabled']|default(False) )

- name: Install Apt packages
  apt:
    name: '{{ item }}'
    update_cache: yes
    cache_valid_time: 86400
    state: present
    install_recommends: no
  with_items: '{{ packages_list }}'
  when: ansible_os_family == 'Debian'

- name: Install RedHat packages
  yum:
    name: '{{ item }}'
    state: present
  with_items: '{{ packages_list }}'
  when: ansible_os_family == 'RedHat'
